parameters:
    pim_base_connector.reader.orm.entity.class:              Pim\Bundle\BaseConnectorBundle\Reader\ORM\EntityReader
    dnd_magento_connector.reader.orm.category.class:         DnD\Bundle\MagentoConnectorBundle\Reader\ORM\CategoryReader
    dnd_magento_connector.reader.orm.attribute.class:        DnD\Bundle\MagentoConnectorBundle\Reader\ORM\AttributeReader

services:
    # readers
    dnd_magento_connector.reader.orm.family:
        class: %pim_base_connector.reader.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.family.class%

    dnd_magento_connector.reader.doctrine.product:
        class: %dnd_magento_connector.reader.doctrine.product.class%
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.completeness'
            - '@pim_transform.converter.metric'
            - '@pim_catalog.object_manager.product'

    dnd_magento_connector.reader.orm.category:
        class: %dnd_magento_connector.reader.orm.category.class%
        arguments:
            - '@pim_catalog.repository.category'

    dnd_magento_connector.reader.orm.attribute:
        class: %dnd_magento_connector.reader.orm.attribute.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute.class%
